In [15]:
import numpy as np

In [16]:
# Input matrices
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

In [17]:
# Addition
print("A + B:\n", A + B)

A + B:
 [[ 8 10 12]
 [14 16 18]]


In [18]:
# Subtraction
print("A - B:\n", A - B)

A - B:
 [[-6 -6 -6]
 [-6 -6 -6]]


In [19]:
# Element-wise Multiplication
print("A * B (Element-wise):\n", A * B)

A * B (Element-wise):
 [[ 7 16 27]
 [40 55 72]]


In [20]:
print(A.shape)
print(B.shape)

(2, 3)
(2, 3)


In [21]:
# Matrix Multiplication (if dimensions allow)

if A.shape[1] == B.shape[0]:
    print("A x B (Matrix Multiplication):\n", np.dot(A, B))
else:
    print("Matrix multiplication not possible.")

Matrix multiplication not possible.


In [22]:
# Transpose
print("Transpose of A:\n", A.T)
print("\nTranspose of B:\n", B.T)

Transpose of A:
 [[1 4]
 [2 5]
 [3 6]]

Transpose of B:
 [[ 7 10]
 [ 8 11]
 [ 9 12]]
